# Generated by Django 3.0.5 on 2020-04-08 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('current_balance', models.DecimalField(decimal_places=0, default=0, max_digits=38)),
                ('POW', models.CharField(max_length=16, null=True)),
                ('in_use', models.BooleanField(default=False)),
                ('application', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=512)),
                ('IP_ADD', models.CharField(max_length=512)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('location_name', models.CharField(default=None, max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('application', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=64)),
                ('application', models.CharField(max_length=64)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='token_api.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=38)),
                ('transaction_hash_sending', models.CharField(max_length=64)),
                ('transaction_hash_receiving', models.CharField(max_length=64)),
                ('POW_send', models.CharField(max_length=16, null=True)),
                ('POW_receive', models.CharField(max_length=16, null=True)),
                ('application', models.CharField(max_length=64)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='token_api.Account')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='token_api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=64)),
                ('application', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('token_id', 'application')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('application', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('device_id', 'application')},
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=38)),
                ('priority', models.IntegerField()),
                ('application', models.CharField(max_length=64)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_device', to='token_api.Device')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='token_api.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='token_api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=64)),
                ('application', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('policy_name', 'application')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='token', to='token_api.Token'),
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='token_api.Wallet'),
        ),
        migrations.CreateModel(
            name='ActionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=64)),
                ('priority', models.IntegerField()),
                ('application', models.CharField(max_length=64)),
                ('allowed_devices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_devices', to='token_api.Account')),
                ('allowed_from_accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_from_accounts', to='token_api.Account')),
                ('allowed_to_accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_to_accounts', to='token_api.Account')),
                ('denied_devices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denied_devices', to='token_api.Account')),
                ('denied_from_accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denied_from_accounts', to='token_api.Account')),
                ('denied_to_accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denied_to_accounts', to='token_api.Account')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_token', to='token_api.Token')),
            ],
            options={
                'unique_together': {('policy_name', 'token', 'application')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('address', 'application')},
        ),
    ]
