# Generated by Django 2.2.12 on 2020-04-22 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=65)),
                ('current_balance', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('POW', models.CharField(default=None, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('priority', models.IntegerField()),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ActionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_set_name', models.CharField(max_length=64)),
                ('priority', models.IntegerField()),
                ('actions', models.ManyToManyField(related_name='actions', to='token_api.Action')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'unique_together': {('application_name',)},
            },
        ),
        migrations.CreateModel(
            name='CustomActionPolicyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_policy_name', models.CharField(max_length=64)),
                ('priority', models.IntegerField()),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_action_policy_application', to='token_api.Application')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('custom_policy_name', 'application')},
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=512)),
                ('node_name', models.CharField(default=None, max_length=256)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_application', to='token_api.Application')),
            ],
        ),
        migrations.CreateModel(
            name='CustomActionPolicy',
            fields=[
                ('customactionpolicybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_api.CustomActionPolicyBase')),
            ],
            bases=('token_api.customactionpolicybase',),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=64, null=True)),
                ('wallet_id', models.CharField(max_length=256)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_application', to='token_api.Application')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='token_api.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('transaction_hash_sending', models.CharField(max_length=64)),
                ('transaction_hash_receiving', models.CharField(max_length=64)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_application', to='token_api.Application')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='token_api.Account')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='token_api.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=64)),
                ('action_sets', models.ManyToManyField(related_name='device_action_sets', to='token_api.ActionSet')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_application', to='token_api.Application')),
            ],
            options={
                'unique_together': {('device_name', 'application')},
            },
        ),
        migrations.AddField(
            model_name='actionset',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_set_application', to='token_api.Application'),
        ),
        migrations.CreateModel(
            name='ActionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=64)),
                ('action_limit', models.IntegerField(default=-1)),
                ('transaction_limit', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('allowed_devices', models.ManyToManyField(blank=True, related_name='allowed_devices', to='token_api.Device')),
                ('allowed_from_accounts', models.ManyToManyField(blank=True, related_name='allowed_from_accounts', to='token_api.Account')),
                ('allowed_to_accounts', models.ManyToManyField(blank=True, related_name='allowed_to_accounts', to='token_api.Account')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_policy_application', to='token_api.Application')),
                ('denied_devices', models.ManyToManyField(blank=True, related_name='denied_devices', to='token_api.Device')),
                ('denied_from_accounts', models.ManyToManyField(blank=True, related_name='denied_from_accounts', to='token_api.Account')),
                ('denied_to_accounts', models.ManyToManyField(blank=True, related_name='denied_to_accounts', to='token_api.Account')),
            ],
            options={
                'unique_together': {('policy_name', 'application')},
            },
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed', models.NullBooleanField(default=False)),
                ('executed_time', models.DateTimeField(default=None, null=True)),
                ('action', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_action', to='token_api.Action')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_history_application', to='token_api.Application')),
                ('policy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_policy', to='token_api.ActionPolicy')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_application', to='token_api.Application'),
        ),
        migrations.AddField(
            model_name='action',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='token_api.Account'),
        ),
        migrations.AddField(
            model_name='action',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='token_api.Account'),
        ),
        migrations.CreateModel(
            name='AccountPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=64)),
                ('send_action_limit', models.IntegerField(default=-1)),
                ('receive_action_limit', models.IntegerField(default=-1)),
                ('send_amount_limit', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('receive_amount_limit', models.DecimalField(decimal_places=16, default=0, max_digits=64)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_policy_application', to='token_api.Application')),
            ],
            options={
                'unique_together': {('policy_name', 'application')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_policies',
            field=models.ManyToManyField(related_name='account_policies', to='token_api.AccountPolicy'),
        ),
        migrations.AddField(
            model_name='account',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_application', to='token_api.Application'),
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='token_api.Wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='actionset',
            unique_together={('action_set_name', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('action_name', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account_name', 'application')},
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=64)),
                ('action_polices', models.ManyToManyField(related_name='action_polices', to='token_api.ActionPolicy')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_application', to='token_api.Application')),
                ('custom_action_polices', models.ManyToManyField(blank=True, related_name='custom_action_polices', to='token_api.CustomActionPolicy')),
            ],
            options={
                'unique_together': {('token_name', 'application')},
            },
        ),
    ]
