# Generated by Django 3.0.5 on 2020-04-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='location_name',
            new_name='node_id',
        ),
        migrations.RemoveField(
            model_name='node',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='node',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='POW_receive',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='POW_send',
        ),
    ]
