# Generated by Django 2.2.12 on 2020-04-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionhistory',
            options={'ordering': ['-executed_time']},
        ),
    ]
