# Generated by Django 2.2.12 on 2020-04-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=31, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=31, default=0, max_digits=64),
        ),
    ]
