# Generated by Django 3.0.5 on 2020-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='device',
        ),
        migrations.AddField(
            model_name='action',
            name='device',
            field=models.ManyToManyField(null=True, related_name='parent_device', to='token_api.Device'),
        ),
        migrations.AlterUniqueTogether(
            name='actionpolicy',
            unique_together={('policy_name', 'application')},
        ),
    ]
