# Generated by Django 3.0.5 on 2020-04-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='accounts',
        ),
    ]
