# Generated by Django 3.0.5 on 2020-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0002_auto_20200409_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
