# Generated by Django 3.0.5 on 2020-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0002_auto_20200408_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='device',
            field=models.ManyToManyField(related_name='parent_device', to='token_api.Device'),
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='allowed_devices',
        ),
        migrations.AddField(
            model_name='actionpolicy',
            name='allowed_devices',
            field=models.ManyToManyField(related_name='allowed_devices', to='token_api.Account'),
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='allowed_from_accounts',
        ),
        migrations.AddField(
            model_name='actionpolicy',
            name='allowed_from_accounts',
            field=models.ManyToManyField(related_name='allowed_from_accounts', to='token_api.Account'),
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='allowed_to_accounts',
        ),
        migrations.AddField(
            model_name='actionpolicy',
            name='allowed_to_accounts',
            field=models.ManyToManyField(related_name='allowed_to_accounts', to='token_api.Account'),
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='denied_devices',
        ),
        migrations.AddField(
            model_name='actionpolicy',
            name='denied_devices',
            field=models.ManyToManyField(related_name='denied_devices', to='token_api.Account'),
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='denied_from_accounts',
        ),
        migrations.AddField(
            model_name='actionpolicy',
            name='denied_from_accounts',
            field=models.ManyToManyField(related_name='denied_from_accounts', to='token_api.Account'),
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='denied_to_accounts',
        ),
        migrations.AddField(
            model_name='actionpolicy',
            name='denied_to_accounts',
            field=models.ManyToManyField(related_name='denied_to_accounts', to='token_api.Account'),
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='token',
        ),
        migrations.AddField(
            model_name='actionpolicy',
            name='token',
            field=models.ManyToManyField(related_name='parent_token', to='token_api.Token'),
        ),
    ]
