# Generated by Django 3.0.5 on 2020-04-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0002_remove_token_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='action_sets',
            field=models.ManyToManyField(related_name='device_action_sets', to='token_api.ActionSet'),
        ),
    ]
