# Generated by Django 3.0.5 on 2020-04-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0003_auto_20200413_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountpolicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='actionpolicy',
            options={},
        ),
        migrations.RemoveField(
            model_name='accountpolicy',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='priority',
        ),
        migrations.AddField(
            model_name='action',
            name='priority',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
