# Generated by Django 3.0.5 on 2020-04-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0003_auto_20200408_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='token',
        ),
        migrations.RemoveField(
            model_name='action',
            name='device',
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='token',
        ),
        migrations.AddField(
            model_name='account',
            name='account_policies',
            field=models.ManyToManyField(related_name='account_policies', to='token_api.AccountPolicy'),
        ),
        migrations.AddField(
            model_name='device',
            name='actions',
            field=models.ManyToManyField(related_name='action', to='token_api.Action'),
        ),
        migrations.AddField(
            model_name='token',
            name='accounts',
            field=models.ManyToManyField(related_name='accounts', to='token_api.Account'),
        ),
        migrations.AddField(
            model_name='token',
            name='action_polices',
            field=models.ManyToManyField(related_name='action_polices', to='token_api.ActionPolicy'),
        ),
    ]
