# Generated by Django 3.0.5 on 2020-04-09 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0004_auto_20200409_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_application', to='token_api.Application'),
        ),
    ]
