# Generated by Django 3.0.5 on 2020-04-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0004_auto_20200414_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='enabled',
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
