# Generated by Django 3.0.5 on 2020-04-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0005_auto_20200415_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
