# Generated by Django 3.0.5 on 2020-04-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0005_auto_20200408_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('action_name', 'application')},
        ),
    ]
