# Generated by Django 3.0.5 on 2020-04-09 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0005_auto_20200409_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_application', to='token_api.Application'),
        ),
        migrations.AlterField(
            model_name='accountpolicy',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_policy_application', to='token_api.Application'),
        ),
        migrations.AlterField(
            model_name='actionpolicy',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_policy_application', to='token_api.Application'),
        ),
        migrations.AlterField(
            model_name='device',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_application', to='token_api.Application'),
        ),
        migrations.AlterField(
            model_name='node',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_application', to='token_api.Application'),
        ),
        migrations.AlterField(
            model_name='token',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='token_application', to='token_api.Application'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramsaction_application', to='token_api.Application'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_application', to='token_api.Application'),
        ),
    ]
