# Generated by Django 3.0.5 on 2020-04-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0006_auto_20200409_0445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountpolicy',
            options={},
        ),
        migrations.RemoveField(
            model_name='accountpolicy',
            name='priority',
        ),
        migrations.AlterField(
            model_name='account',
            name='application',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='accountpolicy',
            name='application',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='action',
            name='application',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='actionpolicy',
            name='application',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='application',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='node',
            name='application',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='token',
            name='application',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='application',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='application',
            field=models.CharField(max_length=64),
        ),
    ]
