# Generated by Django 2.2.12 on 2020-04-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0006_auto_20200415_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account_id', 'application')},
        ),
        migrations.RemoveField(
            model_name='account',
            name='in_use',
        ),
    ]
