# Generated by Django 3.0.5 on 2020-04-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0007_auto_20200409_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='token_api.Application'),
        ),
    ]
