# Generated by Django 2.2.12 on 2020-04-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0007_auto_20200415_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='IP_ADD',
        ),
        migrations.AddField(
            model_name='actionpolicy',
            name='receive_limit',
            field=models.IntegerField(default=-1),
        ),
    ]
