# Generated by Django 3.0.5 on 2020-04-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0007_auto_20200408_2327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actionpolicy',
            unique_together={('policy_name', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('token_id', 'application')},
        ),
    ]
