# Generated by Django 2.2.12 on 2020-04-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0008_auto_20200416_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionpolicy',
            old_name='receive_limit',
            new_name='transaction_limit',
        ),
        migrations.RemoveField(
            model_name='actionpolicy',
            name='send_limit',
        ),
    ]
