# Generated by Django 3.0.5 on 2020-04-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0008_auto_20200408_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
    ]
