# Generated by Django 3.0.5 on 2020-04-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0008_auto_20200409_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
