# Generated by Django 2.2.12 on 2020-04-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0009_auto_20200416_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(max_length=256),
        ),
    ]
