# Generated by Django 3.0.5 on 2020-04-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0011_auto_20200409_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ExampleCustomActionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_policy_name', models.CharField(max_length=64)),
                ('priority', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_action_policy_application', to='token_api.Application')),
            ],
            options={
                'ordering': ['priority'],
                'abstract': False,
                'unique_together': {('custom_policy_name', 'application')},
            },
        ),
    ]
