# Generated by Django 3.0.5 on 2020-04-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0012_auto_20200409_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplecustomactionpolicy',
            options={},
        ),
        migrations.AlterField(
            model_name='account',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_application', to='token_api.Application'),
        ),
        migrations.AlterUniqueTogether(
            name='examplecustomactionpolicy',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CustomActionPolicyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_policy_name', models.CharField(max_length=64)),
                ('priority', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_action_policy_application', to='token_api.Application')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('custom_policy_name', 'application')},
            },
        ),
        migrations.RemoveField(
            model_name='examplecustomactionpolicy',
            name='application',
        ),
        migrations.RemoveField(
            model_name='examplecustomactionpolicy',
            name='custom_policy_name',
        ),
        migrations.RemoveField(
            model_name='examplecustomactionpolicy',
            name='id',
        ),
        migrations.RemoveField(
            model_name='examplecustomactionpolicy',
            name='priority',
        ),
        migrations.AddField(
            model_name='examplecustomactionpolicy',
            name='customactionpolicybase_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_api.CustomActionPolicyBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='custom_action_polices',
            field=models.ManyToManyField(related_name='custom_action_polices', to='token_api.CustomActionPolicyBase'),
        ),
    ]
