# Generated by Django 3.0.5 on 2020-04-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_api', '0013_auto_20200409_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleCustomActionPolicy',
            new_name='CustomActionPolicy',
        ),
    ]
